<!-- Character Encoding & Viewport -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="theme-color" content="#008000"> <!-- ইসলামিক থিমের জন্য সবুজ রঙ -->

<!-- SEO Meta Tags -->
<meta name="description" content="হিফাজতে ইসলাম বাংলাদেশ-এর অফিসিয়াল ওয়েবসাইট। ইসলামী শিক্ষা, দাওয়াত ও সমাজ সংস্কারের জন্য আমাদের প্রচেষ্টা।">
<meta name="keywords" content="ইসলাম, হিফাজত, বাংলাদেশ, দাওয়াত, ইসলামিক শিক্ষা, ধর্মীয় সংগঠন">
<meta name="author" content="হিফাজতে ইসলাম বাংলাদেশ">
<meta name="robots" content="index, follow">

<!-- Open Graph (OG) Meta Tags (Facebook, LinkedIn) -->
<meta property="og:title" content="হিফাজতে ইসলাম বাংলাদেশ">
<meta property="og:description" content="হিফাজতে ইসলাম বাংলাদেশ-এর অফিসিয়াল ওয়েবসাইট।">
<meta property="og:image" content="{{ url(asset('/frontend/images/favicon/apple-touch-icon.png')) }}">
<meta property="og:url" content="{{ url('/') }}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="হিফাজতে ইসলাম বাংলাদেশ">

<!-- Twitter Card Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="হিফাজতে ইসলাম বাংলাদেশ">
<meta name="twitter:description" content="হিফাজতে ইসলাম বাংলাদেশ-এর অফিসিয়াল ওয়েবসাইট।">
<meta name="twitter:image" content="{{ url(asset('/frontend/images/favicon/apple-touch-icon.png')) }}">
<meta name="twitter:site" content="@yourtwitterhandle">

<!-- Favicon & Icons -->
<link rel="icon" type="image/png" href="{{ asset('/frontend/images/favicon/favicon-96x96.png') }}" sizes="96x96">
<link rel="icon" type="image/svg+xml" href="{{ asset('/frontend/images/favicon/favicon.svg') }}">
<link rel="shortcut icon" href="{{ asset('/frontend/images/favicon/favicon.ico') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('/frontend/images/favicon/apple-touch-icon.png') }}">
<meta name="apple-mobile-web-app-title" content="হিফাজত">
<link rel="manifest" href="{{ asset('/frontend/images/favicon/site.webmanifest') }}">

<!-- Canonical URL -->
<link rel="canonical" href="{{ url('/') }}">

<!-- Livewire & Laravel CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" >

<!-- Google Fonts -->
<link href="https://fonts.maateen.me/tiro-bangla/font.css" rel="stylesheet">
<link href="https://fonts.maateen.me/bangla/font.css" rel="stylesheet">


<!-- Styles -->
@vite(['resources/css/app.css', 'resources/js/app.js'])

<!-- Toastr CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

<style>
    .tracking-out-expand{-webkit-animation:tracking-out-expand 5s cubic-bezier(.25,.46,.45,.94) infinite both;animation:tracking-out-expand 5s cubic-bezier(.25,.46,.45,.94) infinite both}
    /* ----------------------------------------------
 * Generated by Animista on 2025-3-13 15:53:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes tracking-out-expand{0%{opacity:1}60%{opacity:.8}100%{letter-spacing:1em;opacity:0}}@keyframes tracking-out-expand{0%{opacity:1}60%{opacity:.8}100%{letter-spacing:1em;opacity:0}}
</style>